[package]
name = "rs_core"
version = "0.1.0"
edition = "2021"

[dependencies]

regex = "1.11.1"
rust-stemmers = "1.2.0"
stop-words = "0.8.1"
uuid = { version = "1", features = ["v4"] }
rand = "0.8"
lopdf = "0.34.0"
